apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-service.yaml  # ExternalName services for cross-namespace routing

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ecombaker-ingress

labels:
  - pairs:
      environment: qa

