apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ingress.yaml
  # cluster-issuer.yaml disabled - SSL/TLS not needed for now

labels:
  - pairs:
      app: ecombaker
      managed-by: kustomize

